name: Security Scan - NutriApp

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Secrets
        run: echo "Secrets cargados correctamente"
        env:
          TEST1: ${{ secrets.JWT_SECRET }}
          TEST2: ${{ secrets.ADMIN_PASSWORD }}

      - name: Run Gemini Security Analysis
        uses: google-github-actions/run-gemini-cli@v1
        with:
          command: /security:analyze
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}